version: "3.8"
services:
  adminer:
    container_name: "go_jwt_adminer"
    image: adminer
    restart: always
    ports:
      - 8085:8080

  db:
    container_name: "go_jwt_db"
    platform: linux/x86_64
    build: 
      context: .
      dockerfile: db.Dockerfile
    networks:
      - default
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DB_HOST: $DB_HOST
      MYSQL_DB_PORT: $DB_PORT
      MYSQL_ROOT_PASSWORD: $DB_PASSWORD
      MYSQL_DATABASE: $DB_NAME
      MYSQL_PASSWORD: $DB_PASSWORD
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
  
  api: 
    container_name: go_jwt_api
    build: 
      context: .
      dockerfile: api.Dockerfile
    restart: always
    ports:
      - 8081:8080
    depends_on:
      - db
    volumes:
      - .:/app/
networks: 
  default:
volumes:
  mysql_data:

  
